### ISSUE TITLE
'python' not found on itiger01

### ISSUE THREAD

**Issue by echoi** [itiger-cluster/itiger-cluster.github.io#2]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

cannot run a simple python code on itiger01

### How to reproduce the bug

Following this example, https://github.com/itiger-cluster/itiger-cluster.github.io/wiki/Submitting-a-Job,
I tried to run a Python script, `animal.py`, with a single line, `print("Dogs bark")`, with the following slurm script:

```SHELL
#!/bin/bash

#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=1G
#SBATCH --partition=bigTiger
#SBATCH --job-name=basicname

echo "*** Running Python on: "$(hostname)

python animal.py
```

### Error messages and logs

```SHELL
*** Running Python on: itiger01
/var/spool/slurmd/job00353/slurm_script: line 10: python: command not found
```

### What operating system are you using?

Linux

### Where are you seeing the problem on?

Deployed site

**Comment by mayirasharif** [comment]
running `module load python` in your terminal should fix this problem. After that, your job will be able to run. Let me know if you're still having trouble! :)

**Comment by echoi** [comment]
Thanks for the response, but `module` was not found on my login terminal:
```SHELL
[echoi2@itiger ~]$ module load python
-bash: module: command not found
```
Should I do something first to be able to load modules?

**Comment by mayirasharif** [comment]
Ok--so perhaps resubmit the bash file you have (without the python line). This should let you gain access to a compute node of the cluster (because you submitted a  working job), where you can run your code. let me know of any more questions!

**Comment by echoi** [comment]
I'd happily start working that way although it doesn't seem to be a long-term solution.

After a few futile attempts with `sbatch`, I found `salloc` command and succeeded in gaining access to itiger01.
However, the problem persists:
'python' command is not found, `module avail` returns only a short list of available modules, and python was not among them. 

What should I try next?

```SHELL
[echoi2@itiger01 ~]$ module load python
ERROR: Unable to locate a modulefile for 'python'
[echoi2@itiger01 ~]$ module avail
---------------------------------------- /usr/share/Modules/modulefiles ----------------------------------------
dot  module-git  module-info  modules  null  use.own

----------------------------------------------- /etc/modulefiles -----------------------------------------------
mpi/mvapich2-x86_64

-------------------------------------------- /usr/share/modulefiles --------------------------------------------
mpi/mpich-x86_64  mpi/openmpi-x86_64

Key:
modulepath
[echoi2@itiger01 ~]$ python
-bash: python: command not found
```

**Comment by mayirasharif** [comment]
here's a link to some template containers you can use. After setting up the container, you can try to install python using **apt install** or **pip install** like how you'd do for a Linux system. They are quite specific examples, but these should have python installed and should get the program running for now.

Hope this helps!
https://github.com/uofm-research-computing/itiger-containers

**Comment by echoi** [comment]
Thank you. I'll try to build my own container. 
I've already started and am encountering the issue of disk quota exceeded. I'll report the details and ask for help by opening a separate issue.
